deny-message-blockbreak: '&c&lYou cannot break this block..'
deny-message-itemdrops: '&c&lYou cannot drop items..'
deny-message-blockplace: '&c&lYou cannot place this block..'
blockbreak: true
blockplace: true
itemdrops: true