# NoGriefing - Configuration file. If a new plugin version comes out and you experience errors, please copy the config.yml from github.
blockbreak: true
blockplace: true
itemdrops: true
enable-blocklog: false
blocklog-save-interval: 60
blocks-to-be-logged: [] 
blocklog: []
deny-message-blockbreak: '&c&lYou cannot break this block..'
deny-message-itemdrops: '&c&lYou cannot drop items..'
deny-message-blockplace: '&c&lYou cannot place this block..'
no-permission-message: '&c&lYou dont have the permission to use this command..'