# NoGriefing - Configuration file 
# If a new version of the plugin comes out, copy and paste the new config from GitHub, to prevent errors.
#Settings, can also be managed in-game.
blockbreak: true
blockplace: true
itemdrops: true

#Blocklog, used to log certain blocks a player places.
enable-blocklog: false
blocklog-save-interval: 60
blocks-to-be-logged: 
     - A block
     - Another block
blocklog: []

# Messages, you can use & colorcodes. Dont forget to start and finish the line with a ' .
deny-message-blockbreak: '&c&lYou cannot break this block..'
deny-message-itemdrops: '&c&lYou cannot drop items..'
deny-message-blockplace: '&c&lYou cannot place this block..'
no-permission-message: '&c&lYou dont have the permission to use this command..'
                    
