# NoGriefing - Configuration file. If a new plugin version comes out and you experience errors, please copy the config.yml from github.
enable-blocklog: false
blocklog: []
blocklog-save-interval: 60
blocks-to-be-logged: []

blockplace: true
blockbreak: true
pvp: true
itempickup: true
itemdrops: true
falldamage: true
drowning: true
fire: true
hunger: true
antitnt: false
inventory-use: true
tool-use: true

deny-message-blockbreak: "&c&lYou cannot break this block.."
deny-message-blockplace: "&c&lYou cannot place this block.."
deny-message-itemdrops: "&c&lYou cannot drop items.."
deny-message-itempickup: "&c&lYou cannot pickup items.."
deny-message-use: "&c&lYou cannot use this here.."
deny-message-bow: "&c&lYou cannot shoot here.."
deny-message-pvp: "&c&lYou cannot damage a %s here.."
no-permission-message: "&c&lYou dont have the permission to use this command.."


disabled-worlds: []
update-check: true
